### ISSUE TITLE
Persistence of research project, including rejected / saved results

### ISSUE THREAD

**Issue by abartov** [projectbenyehuda/sara#13]
A result set contains X results.  

Some X-n results may eventually be manually rejected by the user, and should not appear again, *even* when the search filters change. They are permanently "blacklisted" from appearing in _this_ research project.

Some X-m results may eventually be manually saved/marked by the user with some "add to my research folder" UI element.  Those express the result of the user's human curation. They persist in the research folder *even* if the search filters have changed and they no longer match the criteria (possibly with some UI indication/hint for the user, in case the filter change really did mean they no longer care about such results).

Everything else in X may change if the query is re-run, if filters are changed, etc. The user is not guaranteed to keep seeing them.

**Comment by damisul** [comment]
@abartov , currently we implemented Project CRUD and Ignored Items backend.

From data model point of view we still need to implement 'Favorite' or 'Saved'/'Selected' items functionality.

I believe for the POC we can simply add 'favorite' boolean flag to research_items table.
But we need to keep those items even if query was changed (Or if query is deleted), and currently research Items belongs to query.
So we cannot delete query without deleting all its items.

To manage this situation we can add project_id to response_items table and fill it with data from query.
With this, when we'll try to delete query from project we will delete all items from it where favorite=false. For favorite items we will simply set query_id to nil.

I think this will be enough for POC and MVP, but this solution has one drawback. If several queries will return same item (e.g. same link to PBY work) we will have several copies of same item. With this same item in one query can be marked as favorite, but in other query it will be non-favorite.

We can go for 'maximalist' approach here:
Instead of having response item as children of Query we can make Response_items top level table and use many-to-many relationship to queries (via cross-table). In this case response_items will be shared between different queries (and even different projects), and when item is fetched by some query we should check if it exists in db and create new only if it is not exists (in a case of existing item we can update existing record, to refresh data, or use some different logic here, e.g. refresh only if record was fetched more than X days ago, etc.)
And to mark item as favorite we will need additional table 'favorite_items' with columns 'project_id', 'response_item_id'

It is doable, but I'm not sure if we need to spend so much time here for POC

**Comment by abartov** [comment]
Thank you for this analysis.  I agree the maximalist solution is unnecessary for now; but could we not, upon ingestion of results for a query, compare the external source id to the saved ids of favorited items and set the flag accordingly, to at least keep the multiple copies consistent?

**Comment by damisul** [comment]
Ok, will do.

**Comment by damisul** [comment]
Closing this now. Favorite items PR was the last bit for POC
